
#PBS -N diamond_real_test
#PBS -o log
 
#PBS -e log
   
#PBS -q more      
#PBS -l nodes=1:ppn=20
#PBS -r y                

source /data01/sunxuebo/software/miniconda3/etc/profile.d/conda.sh

conda activate diamond

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=20

/usr/bin/time -o ./time.log -v python3 run_diamond.py -q ../1.preprocess/query_proteins.fasta -d ../data/merged_fasta_pep_no_mammals.fasta -o diamond_results_test.tsv --evalue 1e-5 --threads 20

