#PBS -N NR.7
#PBS -o /data01/sunxuebo/project/zuzhuang/04.annotation/nr/00.nr.pbs/NR.7.pbs.o
#PBS -e /data01/sunxuebo/project/zuzhuang/04.annotation/nr/00.nr.pbs/NR.7.pbs.e
#PBS -q more
#PBS -l nodes=node10:ppn=16
#PBS -l walltime=9999:60:60
#PBS -r y

source /public/software/profile.d/compiler_gnu-7.2.0.sh
echo Working directory is $PBS_O_WORKDIR
echo Running on host `hostname`
echo Start Time is `date`
echo Directory is `pwd`
cd /data01/sunxuebo/project/zuzhuang/04.annotation/nr 
time /public/home/humingliang/software/diamond/diamond-2.0.4/diamond blastp -q /data01/sunxuebo/project/zuzhuang/04.annotation/test.pep.cut/test.pep.7.fa -o /data01/sunxuebo/project/zuzhuang/04.annotation/nr/test.pep.7.fa.nr.blast -k 10 -d /public/home/humingliang/database/gene_function/NR/NR_diamond/NR.fasta -f 0 -e 1e-5 -p 16 -M 20G --quiet
