#!/bin/bash
#PBS -N predict_liver-1
#PBS -o ./
#PBS -e ./
#PBS -q more
#PBS -l nodes=1:ppn=20
#PBS -r y

cd /data01/sunxuebo/project/zuzhuang/01.transdecoder/predict_test
source /public/software/profile.d/compiler_gnu-7.2.0.sh
          export CC=/public/software/compiler/gnu/7.2.0/bin/gcc
          export CXX=/public/software/compiler/gnu/7.2.0/bin/g++
/data01/zhuchenglong/software/python3/Python-3.9.16_build/bin/python3 /data01/wangkun/projects/gene_prediction/version4/test/miniprotGeneAnnotation.py -g sugar_glider.fa -p ../proteins/liver-1_proteins.fasta -t 20 -o ./liver-1.gff
