
#PBS -N blastp
#PBS -o log
 
#PBS -e log
   
#PBS -q more      
#PBS -l nodes=1:ppn=20
#PBS -r y                

source /data01/sunxuebo/software/miniconda3/etc/profile.d/conda.sh

conda activate phylo_env

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=20

/usr/bin/time -o ./time.log -v bash run_blast.sh csnall.fa /data01/sunxuebo/project/zuzhuang/final_genome_gff/sugar_glider.fa /data01/sunxuebo/project/zuzhuang/final_genome_gff/sugar_glider_final_have_exon_7.gtf sg 


