
#PBS -N h5ad2seurat
#PBS -o log
 
#PBS -e log
   
#PBS -q more       
#PBS -l nodes=1:ppn=24
#PBS -l mem=128gb
#PBS -r y                

source /public/home/sunxuebo/software/miniconda3/etc/profile.d/conda.sh


cd $PBS_O_WORKDIR
conda activate new_eatch
/usr/bin/time -o ./time1.log -v python3 h5ad_pre.py
conda activate new_sceasy
/usr/bin/time -o ./time2.log -v Rscript h5ad2seurat.R
conda activate new_eatch
/usr/bin/time -o ./time.log -v  Rscript run_split_rds.R

