#PBS -N Kegg.18
#PBS -o /data01/sunxuebo/project/zuzhuang/04.annotation/kegg/00.kegg.pbs/Kegg.18.pbs.o
#PBS -e /data01/sunxuebo/project/zuzhuang/04.annotation/kegg/00.kegg.pbs/Kegg.18.pbs.e
#PBS -q more
#PBS -l nodes=node4:ppn=16
#PBS -l walltime=9999:60:60
#PBS -r y

source /public/software/profile.d/compiler_gnu-7.2.0.sh
echo Working directory is $PBS_O_WORKDIR
echo Running on host `hostname`
echo Start Time is `date`
echo Directory is `pwd`
cd /data01/sunxuebo/project/zuzhuang/04.annotation/kegg 
time /public/home/humingliang/software/blast/ncbi-blast-2.7.1+/bin/blastp  -query /data01/sunxuebo/project/zuzhuang/04.annotation/test.pep.cut/test.pep.18.fa -out /data01/sunxuebo/project/zuzhuang/04.annotation/kegg/test.pep.18.fa.kegg.blast -num_alignments 10 -db /public/home/humingliang/database/gene_function/kegg/kegg_all_clean.fa  -outfmt 0 -evalue 1e-5  -num_threads 16 
