#PBS -N Swissport.2
#PBS -o /data01/sunxuebo/project/zuzhuang/04.annotation/swissprot/00.swissprot.pbs/Swissport.2.pbs.o
#PBS -e /data01/sunxuebo/project/zuzhuang/04.annotation/swissprot/00.swissprot.pbs/Swissport.2.pbs.e
#PBS -q more
#PBS -l nodes=node4:ppn=16
#PBS -l walltime=9999:60:60
#PBS -r y

source /public/software/profile.d/compiler_gnu-7.2.0.sh
echo Working directory is $PBS_O_WORKDIR
echo Running on host `hostname`
echo Start Time is `date`
echo Directory is `pwd`
cd /data01/sunxuebo/project/zuzhuang/04.annotation/swissprot 
/public/home/humingliang/software/blast/ncbi-blast-2.7.1+/bin/blastp  -query /data01/sunxuebo/project/zuzhuang/04.annotation/test.pep.cut/test.pep.2.fa -out /data01/sunxuebo/project/zuzhuang/04.annotation/swissprot/test.pep.2.fa.swissprot.blast -num_alignments 10 -db /public/home/wubaosheng/projects/01.genome/03.uniprot/swissport/uniprot_sprot.fasta -outfmt 0 -evalue 1e-5  -num_threads 16 
