#PBS -N Trembl.13
#PBS -o /data01/sunxuebo/project/zuzhuang/04.annotation/trembl/00.trembl.pbs/Trembl.13.pbs.o
#PBS -e /data01/sunxuebo/project/zuzhuang/04.annotation/trembl/00.trembl.pbs/Trembl.13.pbs.e
#PBS -q more
#PBS -l nodes=node2:ppn=16
#PBS -l walltime=9999:60:60
#PBS -r y

source /public/software/profile.d/compiler_gnu-7.2.0.sh
echo Working directory is $PBS_O_WORKDIR
echo Running on host `hostname`
echo Start Time is `date`
echo Directory is `pwd`
cd /data01/sunxuebo/project/zuzhuang/04.annotation/trembl 
time /public/home/humingliang/software/diamond/diamond-2.0.4/diamond blastp -d /public/home/humingliang/database/gene_function/trembl/uniprot_trembl.fasta -q /data01/sunxuebo/project/zuzhuang/04.annotation/test.pep.cut/test.pep.13.fa -o /data01/sunxuebo/project/zuzhuang/04.annotation/trembl/test.pep.13.fa.trembl.blast -k 10 -f 0 -e 1e-5 -p 16 -M 20G --quiet
