
#PBS -N MMGpseDEG
#PBS -o log
 
#PBS -e log
   
#PBS -q more  
#PBS -l nodes=1:ppn=1
#PBS -r y
                
export OMP_NUM_THREADS=8

source /public/home/sunxuebo/software/miniconda3/etc/profile.d/conda.sh

conda activate monocle

cd $PBS_O_WORKDIR

/usr/bin/time -o ./time.log -v Rscript run_extra_pseudotime.R

source /data01/sunxuebo/software/miniconda3/etc/profile.d/conda.sh

conda activate py310

/usr/bin/time -o ./time.log -v python3 run_pse_stage_deg.py 

